### PR TITLE
add CodeQL action

### PR DESCRIPTION
**Pull request by YanxuanLiu**
Add CodeQL GitHub action

### CODE REVIEW

**Review by YuanTingHsieh — APPROVED** [review]
Thanks, LGTM!

**Comment by YuanTingHsieh** [comment]
@YanxuanLiu can you sign your commit? thanks

**Review by pxLi — COMMENTED** [review]
CC @YuanTingHsieh @chesterxgchen the CI will start working if we merge this one, so it would be better to take a look at reported issue in this PR before merge, thanks

**Comment by pxLi** [comment]
created a ticket here https://github.com/NVIDIA/NVFlare/issues/727

@YuanTingHsieh @chesterxgchen please help resolve above issue before we merge this one, many thanks!

**Comment by YuanTingHsieh** [comment]
@YanxuanLiu can you sign your commits and do a rebase? thanks!

**Review by YuanTingHsieh — DISMISSED** [review]

**Review by pxLi — DISMISSED** [review]

**Review by pxLi — DISMISSED** [review]

**Review by pxLi — APPROVED** [review]

**Pull request merged**
