### PR TITLE
211 Update hello-monai example

### LINKED ISSUE #211: Update hello-monai example
According to: https://github.com/Project-MONAI/tutorials/pull/546 , the transform `Orientationd` is better to be put before `Spacingd`

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Signed-off-by: Yiheng Wang <vennw@nvidia.com>

This PR fixes #211 

The changes include:

1. put `Orientationd` before `Spacingd` 
2. add `FgBgToIndicesd` transform to cache more info.
3. use `Novograd` to replace `adam` optimizer, and change the learning rate to match the new optimizer
4. use `DiceCELoss` to replace `DiceLoss`
5. decrease `num_rounds` since with the new settings, the convergence speed is faster.

### CODE REVIEW

**Review by holgerroth — APPROVED** [review]
LGTM

**Review by YuanTingHsieh — DISMISSED** [review]
LGTM.

**Comment by YuanTingHsieh** [comment]
@yiheng-wang-nv can you sign the commits?

**Comment by yiheng-wang-nv** [comment]
> @yiheng-wang-nv can you sign the commits? thanks!

Hi @YuanTingHsieh , I already signed the commits before push via using `--signoff`, do I need to do other steps?

**Comment by YuanTingHsieh** [comment]
> > @yiheng-wang-nv can you sign the commits? thanks!
> 
> Hi @YuanTingHsieh , I already signed the commits before push via using `--signoff`, do I need to do other steps?

I am following this: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by yiheng-wang-nv** [comment]
Hi @YuanTingHsieh and @holgerroth , could you please help to re-approve this PR? I tried to add signatures for my commits. Thanks!

**Review by YuanTingHsieh — APPROVED** [review]

**Pull request merged**
