### PR TITLE
Minor fixes to xgboost example

### PR DESCRIPTION
**Pull request by hwpang**
### Description
Two minor fixes:
- Change the `DATASET_ROOT` environment variable in the notebook to `$HOME/dataset`. This is to be consistent with the path used in other scripts in this example, such as `NVFlare/examples/advanced/xgboost/prepare_data.sh` and `NVFlare/examples/advanced/xgboost/histogram-based/run_experiment_centralized.sh`.
- The `training_mode` argument should be `training_algo`:

```
    parser.add_argument(
        "--training_algo", type=str, default="bagging", choices=list(ALGO_DIR_MAP.keys()), help="Training algorithm"
    )
```

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by hwpang** [comment]
> @hwpang question: why prefer to use HOME directory to /data directory ? HOME directory is usually in the source code directory which something mixing the data and code together. /data at least refer the data in a different location, more close to the real case.

Thanks for the question. I was trying to make the path to the dataset consistent throughout this example. In the other scripts used in this example, the `$HOME/dataset` is assumed to be the directory of the dataset. For example, in `NVFlare/examples/advanced/xgboost/prepare_data.sh`, it looks for the dataset in `$HOME/dataset`:

```
DATASET_PATH="$HOME/dataset/HIGGS.csv"
OUTPUT_PATH="/tmp/nvflare/xgboost_higgs_dataset"
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ ! -f "${DATASET_PATH}" ]
then
    echo "Please check if you saved HIGGS dataset in ${DATASET_PATH}"
fi
```

I don't have a strong preference of `$HOME/dataset` vs. `/data`, as long as the path is consistent with other scripts used in this example.

**Comment by ZiyueXu77** [comment]
> > @hwpang question: why prefer to use HOME directory to /data directory ? HOME directory is usually in the source code directory which something mixing the data and code together. /data at least refer the data in a different location, more close to the real case.
> 
> Thanks for the question. I was trying to make the path to the dataset consistent throughout this example. In the other scripts used in this example, the `$HOME/dataset` is assumed to be the directory of the dataset. For example, in `NVFlare/examples/advanced/xgboost/prepare_data.sh`, it looks for the dataset in `$HOME/dataset`:
> 
> ```
> DATASET_PATH="$HOME/dataset/HIGGS.csv"
> OUTPUT_PATH="/tmp/nvflare/xgboost_higgs_dataset"
> SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
> 
> if [ ! -f "${DATASET_PATH}" ]
> then
>     echo "Please check if you saved HIGGS dataset in ${DATASET_PATH}"
> fi
> ```
> 
> I don't have a strong preference of `$HOME/dataset` vs. `/data`, as long as the path is consistent with other scripts used in this example.

Thanks for noticing this! @chesterxgchen at the time we wanted to avoid creating new folders within examples, and avoid putting HIGGS to "/tmp" since it is big, so arbitrarily chose '$HOME'

**Comment by YuanTingHsieh** [comment]
I think consistency throughout notebook and the example folder is good, so this PR LGTM

**Review by ZiyueXu77 — APPROVED** [review]
LGTM

**Pull request merged**
