### PR TITLE
[2.5] cherry pick explanability part of xgboost 

### PR DESCRIPTION
**Pull request by ZiyueXu77**
Fixes # .

### Description

Cherry pick from main

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by nvidianz — DISMISSED** [review]
This may have merge conflict with #3099

**Review by YuanTingHsieh — CHANGES_REQUESTED** [review]
While this change is good, let's use https://github.com/NVIDIA/NVFlare/pull/3099 to get all the changes in

**Comment by ZiyueXu77** [comment]
> While this change is good, let's use #3099 to get all the changes in

sounds good!

**Comment by ZiyueXu77** [comment]
use 3099  instead

**Pull request closed without merging**
