### PR TITLE
2.0 global model init using ResponseProcessor

### PR DESCRIPTION
**Pull request by holgerroth**
Update hello-pt example to let client initialize the global model using new `InitializeGlobalWeights` workflow.

### CODE REVIEW

**Comment by holgerroth** [comment]
> 

This PR is for the patch to 2.0 branch. #1105 is for the dev branch.

**Comment by Chesterguan** [comment]
Hi, seems the hello-pt example application cannot run.

The error is : `Cannot find component class "InitializeGlobalWeights"`

**Comment by holgerroth** [comment]
> Hi, seems the hello-pt example application cannot run.
> 
> The error is : `Cannot find component class "InitializeGlobalWeights"`

Hi @Chesterguan , which nvflare version are you using?

**Comment by Chesterguan** [comment]
Hi Holger, thanks for the response.

The `nvflare` version is `2.2.3`. 
To reproduce the problem: I was using the `nvflare simulator ./workspace -n 2 -t 2 ./hello-pt`

**Comment by Chesterguan** [comment]
I was trying to remove both `get_weights` task and `pre_training` workflow from configuration json files. 
The application seems to be able to run again, but did not print anything and stuck.

**Comment by YuanTingHsieh** [comment]
@Chesterguan I apologize for any confusion.
For 2.2.X version please refer to the examples in here: https://github.com/NVIDIA/NVFlare/tree/2.2/examples

**Comment by Chesterguan** [comment]
@YuanTingHsieh Hi YuanTing! Thanks for the clarification. I will do more tests.

**Comment by holgerroth** [comment]
2.2.3 doesn't have that workflow https://github.com/NVIDIA/NVFlare/tree/2.2.3/nvflare/app_common/workflows
The example on the dev branch will not work with that version. Either use the [2.2.3 example](https://github.com/NVIDIA/NVFlare/blob/2.2.3/examples/hello-pt/app/config/config_fed_server.json) or install the current dev branch using `pip install -e $NVFLARE_HOME`

**Comment by Chesterguan** [comment]
Appreciate! @holgerroth

**Pull request merged**
