### PR TITLE
[2.5] Fix simulator result path

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
### Description

Fix simulator result path

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
@ZiyueXu77 Do we need to correct the path for BRAT18 and prostate as well?

**Comment by ZiyueXu77** [comment]
> @ZiyueXu77 Do we need to correct the path for BRAT18 and prostate as well?

For brats, I don't think so since we directly use the root folder "tensorboard --logdir='./workspace_brats'"
But for prostate, we may need to update the path in https://github.com/NVIDIA/NVFlare/blob/main/examples/advanced/prostate/result_stat/plot_tensorboard_events.py (although we used blob to search for the record)

**Review by ZiyueXu77 — APPROVED** [review]
looks good

**Pull request merged**
