### PR TITLE
Bump up the version of monai-nvflare package to 0.2.9

### PR DESCRIPTION
**Pull request by IsaacYangSLA**
### Description

Also update its nvflare version to ~=2.5.0rc1

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by YuanTingHsieh — DISMISSED** [review]
LGTM

**Review by nvkevlu — APPROVED** [review]
Thank you, LGTM

**Pull request merged**
