### PR TITLE
Don't catch BaseException

### PR DESCRIPTION
**Pull request by taleinat**
### Description

`BaseException` includes `SystemExit` and `KeyboardInterrupt`, so catching it can interfere with proper process termination. It also includes `GeneratorExit` which can cause some very strange behaviors.

Catching `BaseException` should only be necessary in highly exceptional cases. Clearly, though, in this codebase it is used wherever `except Exception` would normally be used, i.e. to catch any type of "normal" exception (what a lovely oxymoron!).

I reviewed some of the places where this replacement is done in this PR, but not all of them.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by yanchengnv** [comment]
We do need a complete review on all such cases. For most places, we should use Exception.  There might be very few places that we do need to catch everything, including KeyboardInterrupt. But these should not be the norm.

**Comment by YuanTingHsieh** [comment]
Thanks for the PR!

@yhwen please confirm this change is OK with nvflare/private codes.
@IsaacYangSLA please confirm this change is OK with nvflare/dashboard and nvflare/lighter.

Other parts LGTM.

**Comment by IsaacYangSLA** [comment]
OK on dashboard/overseer/lighter.

**Review by nvidianz — APPROVED** [review]

**Review by yhwen — APPROVED** [review]

**Review by yhwen — APPROVED** [review]

**Pull request merged**
