### PR TITLE
Add secure argument to Task and set secure argument in cell's call.

### PR DESCRIPTION
**Pull request by IsaacYangSLA**
### Description

This PR handles the new argument 'secure' in cell's methods.  And adds the new argument 'secure' in Task so client task control can set it in Task.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [x] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by yanchengnv — CHANGES_REQUESTED** [review]
The changes are good, but not enough. You only changed server_engine_spec.py, there are concrete classes that implement this spec. All these classes need to be changed. You can do a search on "send_aux_request" and find these places.

**Comment by IsaacYangSLA** [comment]
Thanks.  Let me go through all places.

**Review by yanchengnv — APPROVED** [review]
LGTM

**Review by YuanTingHsieh — APPROVED** [review]
LGTM

**Pull request merged**
