### PR TITLE
Update streaming widget to use just function but not component

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
- Update streaming widget to use function 
- Update tb_streaming app in test_apps

### CODE REVIEW

**Review by IsaacYangSLA — DISMISSED** [review]
The only thing that might need another refactor is the EVENT="log_analytics" because the json is using the string.

**Comment by IsaacYangSLA** [comment]
@YuanTingHsieh , can you check https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification and have the commit signed?

**Comment by YuanTingHsieh** [comment]
> The only thing that might need another refactor is the EVENT="log_analytics" because the json is using the string.

What do we want about this?

**Review by IsaacYangSLA — APPROVED** [review]
Thanks for this PR.  LGTM.

**Pull request merged**
