### PR TITLE
[2.4] Add client api integration tests 

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
### Description

- Adds test stage client_api and client_api_qa
- Adds corresponding test jobs

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
They are intended, Are you suggesting I change them to longer names to reflect what they are? 

For example 
"swarm_cse_pt_with_xxx"

**Review by SYangster — APPROVED** [review]
qa_job_xxx can be renamed if it makes sense, otherwise LGTM

**Comment by YuanTingHsieh** [comment]
thanks, let me rename them later

**Pull request merged**
