### PR TITLE
Cleanup the PT example

### PR DESCRIPTION
**Pull request by madil90**
- Use log_error instead of exception when appropriate.
- Improve organization/docstrings
- Fix some small bugs
- Use consistent variable names

### CODE REVIEW

**Comment by yhwen** [comment]
Adil, could you please resolve the conflicts?

**Comment by IsaacYangSLA** [comment]
@madil90 , we wouldn't write to your branch and were unable to resolve the conflict for you.  Can you rebase it to upstream/main and make sure it's clean?  Thanks.

**Comment by madil90** [comment]
All issues resolved and rebased

**Comment by IsaacYangSLA** [comment]
LGTM.  @yhwen , if it's OK with you, we can merge this.

**Pull request merged**
