### PR TITLE
[2.4] Add job template dir in setup_poc.ipynb

### PR DESCRIPTION
**Pull request by hwpang**
Fixes # .

### Description

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by ZiyueXu77** [comment]
seems down everywhere using this 'archive' link, I found this
https://mlphysics.ics.uci.edu/data/higgs/ hopefully it can last longer

**Comment by ZiyueXu77** [comment]
> > seems down everywhere using this 'archive' link, I found this https://mlphysics.ics.uci.edu/data/higgs/ hopefully it can last longer
> 
> can you create PRs to update the higgs link, we have to update that PRs, before this one can be merged.

sure, doing it now

**Comment by ZiyueXu77** [comment]
> > > seems down everywhere using this 'archive' link, I found this https://mlphysics.ics.uci.edu/data/higgs/ hopefully it can last longer
> > 
> > 
> > can you create PRs to update the higgs link, we have to update that PRs, before this one can be merged.
> 
> sure, doing it now

done

**Review by YuanTingHsieh — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
