### PR TITLE
update admin logout for ha

### PR DESCRIPTION
**Pull request by SYangster**
- add user configured admin timeout
- fix bye/shutdown

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
If the server dies and never comeback, the admin will not timeout?

**Comment by YuanTingHsieh** [comment]
If the server dies and never comeback, the admin will not timeout?

**Comment by nvkevlu** [comment]
Sorry for the conflicts, you can delete the comment that is in cli.py.

**Comment by SYangster** [comment]
> If the server dies and never comeback, the CLI will not timeout and close itself?

> If the server dies and never comeback, the admin will not timeout?

I originally had this, but we decided that there are no guarantees on how long the switch will take (wherein it cannot reach a server), so instead we keep waiting.

**Comment by YuanTingHsieh** [comment]
Got it, so we decide not to support #194 ?

**Pull request closed without merging**
