### PR TITLE
F3 Streaming Code Rewrite

### PR DESCRIPTION
**Pull request by nvidianz**
Fixes FLARE-2241

1. Refactored F3 streaming code so it's more object oriented, easier to debug.
2. Fixed a few corner cases found during testing with a testing driver that injects duplicate packets.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
@nvidianz can you break this down into 2 PRs?
One the same as #2956 so we can easier review that and approve.
Other stuff go into the other PR.

**Comment by nvidianz** [comment]
> @nvidianz can you break this down into 2 PRs? One the same as #2956 so we can easier review that and approve. Other stuff go into the other PR.

Good idea! This PR only contains the changes in #2956. Will create another PR for the other changes.

**Review by YuanTingHsieh — APPROVED** [review]
LGTM

**Pull request merged**
