### PR TITLE
Honor optional flag at streaming level

### PR DESCRIPTION
**Pull request by nvidianz**
Fixes #FLARE-2148 

### Description

Honor optional flag at streaming layer. When the message is marked as optional, all errors are logged at debug level.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by yhwen — APPROVED** [review]
My tests show the error log went away for the QA test cases.

**Review by YuanTingHsieh — APPROVED** [review]
LGTM

**Pull request merged**
