### PR TITLE
Ha fix

### PR DESCRIPTION
**Pull request by yhwen**
Fixes # .

Fix the FCI integration HA server switch issue. (along with the underneath F3 communication layer change.)

### Description

Enable the HA server switch for the FCI APIs integration. 
Reasons for the HA failure:

- server job runner process not properly shutdown when the server parent process terminated.
- Client communication (pull_task and heartbeat, submit_result, )not properly timeout.
- Client cell connection to the dead server not properly dropped. (Fixed in https://github.com/NVIDIA/NVFlare/pull/1399) 
- Cellnet add another protection to ensure the cell connection drop. (https://github.com/NVIDIA/NVFlare/pull/1405)

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by IsaacYangSLA — APPROVED** [review]
Basically, this is using check_parent_alive to monitor server so once the server dies, it closes the runner.  I think it looks good to me.

**Comment by yhwen** [comment]
> the changes looks good to me, but what's the main cause of the original issue, I only see some time out changes and new event monitoring.

Updated the PR description.

**Review by nvidianz — APPROVED** [review]
LGTM

**Pull request merged**
