### PR TITLE
Improvement on model diff computation

### PR DESCRIPTION
**Pull request by ZiyueXu77**
Fixes # .

### Description

update the computation of model diff from using "-" to using np.subtract

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by holgerroth** [comment]
@ZiyueXu77, could you also change this line https://github.com/NVIDIA/NVFlare/blob/8c79b7058c6663d4ac96a7b64de27e007769ae0e/research/quantifying-data-leakage/src/nvflare_gradinv/learners/cxr_learner.py#L458?

**Comment by ZiyueXu77** [comment]
> @ZiyueXu77, could you also change this line
> 
> https://github.com/NVIDIA/NVFlare/blob/8c79b7058c6663d4ac96a7b64de27e007769ae0e/research/quantifying-data-leakage/src/nvflare_gradinv/learners/cxr_learner.py#L458
> 
> ?

sure! somehow pycharm didn't catch it...

**Review by holgerroth — APPROVED** [review]
Looks good. @chesterxgchen confirmed it to be okay to merge offline.

**Pull request merged**
