### PR TITLE
Add XGB explainability output

### PR DESCRIPTION
**Pull request by ZiyueXu77**
Fixes # .

### Description

Add SHAP plots for feature importance and model explainability 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by YuanTingHsieh — COMMENTED** [review]
LGTM, have you tried the other xgboost examples to see if they still work?

Thanks

**Comment by ZiyueXu77** [comment]
> LGTM, have you tried the other xgboost examples to see if they still work?
> 
> Thanks
tried related (histogram-based) examples and they worked fine, this one only added an extra output, so did not cause any issues

**Review by YuanTingHsieh — APPROVED** [review]
LGTM

**Pull request merged**
