### PR TITLE
Fix `project.yml` master templates

### PR DESCRIPTION
**Pull request by apatole**
Fixes # .
This change just fixes comments in `project.yml` templates to make it more clear.

### Description
The `project.yml` generated by `nvflare provision` command has comments `change overseer.example.com to the FQDN of the overseer` and `change example.com to the FQDN of the server` but the actual values nowhere has `example.com` mentioned and it is confusing.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Quick tests passed locally by running `./runtest.sh`.

### CODE REVIEW

**Review by IsaacYangSLA — DISMISSED** [review]
Thanks for the PR to improve the quality of codes.  We may later add more comments on that template to describe the 'name' field in more details.

**Comment by apatole** [comment]
Thanks @IsaacYangSLA for the review, please also help with the merge as it seems `blossom-ci` never passes and I can't merge it from my side. Thanks.

**Comment by apatole** [comment]
Just rebased the change...

**Comment by apatole** [comment]
Rebased again...

**Comment by YuanTingHsieh** [comment]
@apatole can you sign your commit? thanks

**Comment by apatole** [comment]
> @apatole can you sign your commit? thanks

Done.

**Comment by apatole** [comment]
I had signed the commit, not sure why it is not showing it as verified.

**Comment by apatole** [comment]
@YuanTingHsieh Now it is showing commit as verified. Please help triggering workflows once and merge, sorry for the inconvenience.

**Review by YuanTingHsieh — APPROVED** [review]
thanks, LGTM

**Comment by IsaacYangSLA** [comment]
After a second thought, I think this PR might break our tests because the default names of server/overseer in project.yml change.  Those default names are used in various test cases.  A better PR will be to change the comment.

**Comment by YuanTingHsieh** [comment]
@IsaacYangSLA you are right.
@apatole can you instead change the comment to make things clearer? thank you

**Review by YuanTingHsieh — CHANGES_REQUESTED** [review]
As Isaac pointed out, there are some tests use these names.

Can you instead change the comment to make things clearer? thank you

**Comment by apatole** [comment]
> As Isaac pointed out, there are some tests use these names.
> 
> Can you instead change the comment to make things clearer? thank you

@YuanTingHsieh / @IsaacYangSLA Done, just modified comments instead, thanks.

**Review by YuanTingHsieh — APPROVED** [review]
Thanks for this change, this is going to help a lot for the user experiences.

**Pull request merged**
