### PR TITLE
Fix filesystem storage object creation bugs

### PR DESCRIPTION
**Pull request by SYangster**
- disallow creation of object at nonempty directory
- disallow creation of object inside preexisting object

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
This newly added logic LGTM.


I have questions regarding the existing codes, in some places I see

`full_uri = os.path.join(self.root_dir, uri.lstrip("/"))`


By doing this, if the URI is "/home/XXX" and the root is "hello" we will change this into "hello/home/XXX"?

So we are assuming the leftmost "/" is translated to self.root_dir?

**Comment by YuanTingHsieh** [comment]
This newly added logic LGTM.


I have questions regarding the existing codes, in some places I see

`full_uri = os.path.join(self.root_dir, uri.lstrip("/"))`


By doing this, if the URI is "/home/XXX" and the root is "hello" we will change this into "hello/home/XXX"?

So we are assuming the leftmost "/" is translated to self.root_dir?

**Comment by SYangster** [comment]
Yes self.root_dir is by default "/", I can enforce that self.root_dir is an absolute path.

**Review by YuanTingHsieh — APPROVED** [review]

**Comment by SYangster** [comment]
Replaced with #325

**Pull request closed without merging**
