### PR TITLE
Fix code format [skip ci]

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
### Description

- Fix code format in research folder

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by holgerroth — APPROVED** [review]
Makes sense. Maybe we should enforce the code style for the research folder as well?

**Comment by YuanTingHsieh** [comment]
@holgerroth I guess that mostly depends on you and @ZiyueXu77 , what do you guys think?

**Comment by holgerroth** [comment]
> 

Let's enforce it.

**Review by ZiyueXu77 — APPROVED** [review]

**Comment by ZiyueXu77** [comment]
agree, let's enforce it

**Pull request merged**
