### PR TITLE
Added cross_validation config to the args.

### PR DESCRIPTION
**Pull request by yhwen**

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
Is this a bug fix or new feature?

If it is a new feature we should merge this back into 2.1 branch?

**Review by IsaacYangSLA — APPROVED** [review]
I guess this is to set the default location of cross_validation configuration file.  The actual loading is up to the client.

**Comment by yhwen** [comment]
> Is this a bug fix or new feature?
> 
> If it is a new feature we should merge this back into 2.1 branch?

This is for a bug fix in Clara-train 4.1 cross-validation. The cross-validation overwrites the client validation TB events.

**Comment by yanchengnv** [comment]
Yuhong and I discussed. This PR is NOT needed.

**Comment by yanchengnv** [comment]
Cross site validation is NOT a concept of NVFLARE core. The changes will be in other place (Clara Train).

**Pull request closed without merging**
