### PR TITLE
Reject legacy job

### PR DESCRIPTION
**Pull request by IsaacYangSLA**
### Description

This PR implements a feature that when users submit legacy jobs (no meta.json, no job folder, only app folder), the server rejects them with error messages.

```
> submit_job s_app
Error: ValueError: meta.[json|conf|yml] not existing for job s_app, possible in legacy job format.  Please upgrade the job structure.
```

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by YuanTingHsieh — DISMISSED** [review]
Thanks LGTM

**Review by yanchengnv — APPROVED** [review]
Looks good.

**Review by YuanTingHsieh — DISMISSED** [review]

**Review by YuanTingHsieh — APPROVED** [review]

**Pull request merged**
