### PR TITLE
Remove self-hosted runners and use only blossom ci

### LINKED ISSUE #649: [CICD] Migrate to Blossom-ci
Blossom-ci pre-merge pipeline runs well. It's time to migrate from self-hosted runner CI to blossom-ci gradually. 
We divided the migration into the following stages:

- [x] Enable blossom-ci as an optional PR check (manual trigger required) and let it run for a few weeks
- [ ] Switch self-hosted runner CI as an optional check, and blossom-ci as required one
- [ ] remove self-hosted runners and related workflow files to meet security requirements
- [ ] blossom-ci for pre-merge only

@chesterxgchen @YuanTingHsieh Could you help to confirm the timelines and completion conditions for each stage?
cc @pxLi

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
Fix #649 

- Fix runtest.sh
- Use GitHub hosted runners instead of self-hosted runners
- Update workflow yaml

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
@pxLi @YanxuanLiu Does this match what we are thinking?

Or I should modify the condition to always trigger Blossom-CI tests?

**Review by pxLi — APPROVED** [review]
LGTM

**Review by nvkevlu — APPROVED** [review]

**Pull request merged**
