### PR TITLE
Change BaseException to Exception

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
### Description

Change BaseException to Exception

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
@chesterxgchen thanks for the input, I will also need to change main/2.3 PRs that was added by Tal.

What about this:

APP side: We use "Exception":
- nvflare/api
- nvflare/app_common
- nvflare/app_opt
- examples
- research
- integration

SYSTEM side: we use "BaseException":
- nvflare/dashboard
- nvflare/fuel
- nvflare/ha
- nvflare/lighter
- nvflare/private
- nvflare/security
- nvflare/tool
- nvflare/widgets

**Comment by YuanTingHsieh** [comment]
This PR is just porting the https://github.com/NVIDIA/NVFlare/pull/1743 into dev branch.

Will wait for @yhwen to verify things are good on branch 2.3 then we can merge this.

**Comment by yhwen** [comment]
> This PR is just porting the #1743 into dev branch.
> 
> Will wait for @yhwen to verify things are good on branch 2.3 then we can merge this.

2.3 branch simulator tests ran okay with these changes.

**Pull request merged**
