### PR TITLE
Add information about enable_byoc and allow_byoc

### PR DESCRIPTION
**Pull request by nvkevlu**
Update documentation to add information about enable_byoc and allow_byoc and what they do in the provisioning process, and have the apidocs pages display better with module-first.

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
LGTM, do we have any place explain what BYOC is in full? 
Bring-Your-Own-Component, or Bring Your Own Code.

**Review by YuanTingHsieh — DISMISSED** [review]
LGTM

**Review by IsaacYangSLA — DISMISSED** [review]

**Comment by IsaacYangSLA** [comment]
Thanks, @nvkevlu .  This PR clearly explained the terms, allow_byoc and enable_byoc.

**Comment by nvkevlu** [comment]
Needed to sign the commit, all the changes are the same.

**Review by yhwen — APPROVED** [review]

**Review by YuanTingHsieh — APPROVED** [review]
LGTM.

**Pull request merged**
