### PR TITLE
Fix simulator package issue [skip ci]

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
- Move "log.config" to simulator module level
- Include "log.config" in wheel
- Change hardcoded values inside simulator to use pre-defined constants

### CODE REVIEW

**Comment by yhwen** [comment]
This PR moved the log.config from “simulator/resource” folder into the “simulator” folder directly. It’s better to separate the non Python codes into a separate “resource” folder, not mixing the config files and Python source codes together.

**Comment by YuanTingHsieh** [comment]
If we put log.config in the simulator/resource folder, we will need to add an __init__.py there to make the packager to pick up this log.config file, that is not good.

And to the point of "mixing the config files and Python source codes together."
If the log.config is inside the nvflare root folder, we are already mixing configs with Python source codes.

**Pull request merged**
