### PR TITLE
[2.4] Use full path for DhPSITaskHandler

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
### Description

Fix 4568016
Use full path for DhPSITaskHandler to avoid confusion

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by SYangster — DISMISSED** [review]
Do we also want to change to use the full path for [psi](https://github.com/NVIDIA/NVFlare/blob/2.4/examples/advanced/psi/user_email_match/jobs/user_email_match/app/config/config_fed_client.conf) and [finance](https://github.com/NVIDIA/NVFlare/blob/2.4/examples/advanced/finance/jobs/vertical_xgb_psi/app/config/config_fed_client.json) examples?

**Comment by YuanTingHsieh** [comment]
good point, let me do something there.

**Review by SYangster — APPROVED** [review]
Thanks LGTM

**Pull request merged**
