### PR TITLE
Local folder from provisioning

### PR DESCRIPTION
**Pull request by IsaacYangSLA**

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
do we need to wait for https://github.com/NVIDIA/NVFlare/pull/763?

**Comment by IsaacYangSLA** [comment]
Yes.  If #763 has the same args for resource manager, we have to merge this and that one at the same time.

**Review by YuanTingHsieh — APPROVED** [review]
Thanks, LGTM

**Review by nvkevlu — DISMISSED** [review]
Thanks, LGTM

**Comment by IsaacYangSLA** [comment]
This PR does not pass blossom-ci due to files being moved out from startup folders.  Since it won't pass until all other related changes are done, we have to decide how to deal with such issue (allow CI failing for some PR while waiting for others or have all PR merged in other branch, then do a big PR to dev?)

**Review by yhwen — APPROVED** [review]

**Pull request merged**
