### PR TITLE
Optional flag and bug fixes

### PR DESCRIPTION
**Pull request by nvidianz**
Fixes FLARE-1594

1. Added optional flag.
2. Made streaming parameter configurable
3. Added info log for connection creation/closing
4. Fixed a bug when error received before future is created.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Review by IsaacYangSLA — COMMENTED** [review]
I am not sure if there is document describing what files and what names users can use to set values to override the defaults.

**Comment by nvidianz** [comment]
> I am not sure if there is document describing what files and what names users can use to set values to override the defaults.

Where shall we document this? The parameters can be placed inside local/comm_config.json.

**Comment by IsaacYangSLA** [comment]
> > I am not sure if there is document describing what files and what names users can use to set values to override the defaults.
> 
> Where shall we document this? The parameters can be placed inside local/comm_config.json.

I think you may need to update some rst file in docs folder so users know the syntax of that file and the meaning of important variables.

**Review by yanchengnv — APPROVED** [review]
LGTM

**Pull request merged**
