### PR TITLE
set the peer_ctx to private.

### PR DESCRIPTION
**Pull request by yhwen**

### CODE REVIEW

**Comment by yhwen** [comment]
> what does private here mean ?

Private means only keep locally, not going to share with remote side (server / client)

**Comment by yhwen** [comment]
> @yanchengnv can probably review this. seems ok to me, but I am not sure the impact.

The same fix has been in 2.2.0 release. https://github.com/NVIDIA/NVFlare/pull/880

**Review by yanchengnv — APPROVED** [review]
LGTM

**Pull request merged**
