### PR TITLE
sync 2.2 branch changes back to dev for CLI commands [skip ci]

### PR DESCRIPTION
**Pull request by chesterxgchen**

### CODE REVIEW

**Comment by YuanTingHsieh** [comment]
Thanks for the PR.
simulator runner is being updated in #816 and #817 , I think this PR should wait on that change.

**Review by YuanTingHsieh — CHANGES_REQUESTED** [review]
let's wait for #816 and #817

**Comment by YuanTingHsieh** [comment]
@chesterxgchen can you resolve the conflicts? thanks

**Review by nvidianz — APPROVED** [review]

**Review by YuanTingHsieh — APPROVED** [review]

**Pull request merged**
