### PR TITLE
Include exception type in error logs

### PR DESCRIPTION
**Pull request by taleinat**
### Description

The `str()` of an exception normally doesn't include its type. Including the type of the exception is very useful.

In the rare cases of exceptions with no details in their string representation, this is especially significant.

This is similar to the format used in Python exception tracebacks:

```python
>>> int("a")
Traceback (most recent call last):
  File "<pyshell#>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'a'

>>> try:
	int("a")
except ValueError as exc:
	print(str(exc))

invalid literal for int() with base 10: 'a'
```

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

### CODE REVIEW

**Comment by taleinat** [comment]
>  do you mind to submit another PR for the dev branch ?

Sure.

**Comment by taleinat** [comment]
Upon further consideration, I think it makes sense to also include the exception's traceback if `is_secure()` is false.

We just ran into a case where the traceback would be where the truly useful information was in such an error.

What do you think?

**Comment by YuanTingHsieh** [comment]
@taleinat we have "secure_format_traceback" method here, do you think that serves your need?
Or you suggest have "secure_format_exception" absorb "secure_format_traceback" method?

**Comment by taleinat** [comment]
Thanks for the pointer @YuanTingHsieh! Yes I think `secure_format_traceback()` or `secure_log_traceback()` would be good here. I'll update this PR.

**Comment by taleinat** [comment]
> Thanks for the pointer @YuanTingHsieh! Yes I think `secure_format_traceback()` or `secure_log_traceback()` would be good here.
> 
> I'll create another PR.

Actually, I see that on the dev branch `secure_log_traceback()` has been added for configuration errors, which is where we found it to be missing. And that's already included in v2.3, but I don't see it on the v2.2 branch. So apparently no extra PR is needed.

**Comment by YuanTingHsieh** [comment]
@taleinat can you fix the unit test failure?
I believe it is cause by this one: https://github.com/NVIDIA/NVFlare/blob/dev/tests/unit_test/fuel/utils/component_builder_test.py#L79-L82 

You can run test locally using ./runtest.sh

Thanks

**Review by YuanTingHsieh — CHANGES_REQUESTED** [review]
please fix the unit test thanks!

**Comment by YuanTingHsieh** [comment]
Thanks, Changes move to #1785, I fix the unit test there

**Comment by taleinat** [comment]
Thanks @YuanTingHsieh, I couldn't get to fixing these before today...

**Pull request closed without merging**
